import { useState , useEffect } from "react";
import "./ReviewPage.css"

function ReviewForm({ loggedInUser, onClose, onSave, editingReview }) {
    const [username, setUsername] = useState("");
    const [name, setName] = useState("");
    const [levelName, setLevelName] = useState("");
    const [rating, setRating] = useState(0);
    const [comment, setComment] = useState("");
    const today = new Date().toISOString().split("T")[0];
    const [date] = useState(today);
    const [successMsg, setSuccessMsg] = useState("");

    // converting levelId to levelName
     function getLevelName(levelId) {
    if (levelId === 1) return "Beginner";
    if (levelId === 2) return "Intermediate";
    return "Advanced";
    }

   // Mapping levelname with id for backend level id values
    const levelMap = {
    Beginner: 1,
    Intermediate: 2,
    Advanced: 3
    };

    //prefillied form when do editing
      useEffect(() => {
    if (editingReview) {
      setUsername(editingReview.username);
      setName(editingReview.name);
      setLevelName(editingReview.level?.name || "");
      setRating(editingReview.rating);
      setComment(editingReview.comment);
    } else if (loggedInUser) {
    setUsername(loggedInUser); 
    }
  }, [editingReview , loggedInUser]);     

    function handleSubmit(e) {
    e.preventDefault();

    const newReview = {
      id: editingReview ? editingReview.id : undefined, 
      username,
      name,
      levelId: levelMap[levelName], 
      rating,
      comment,
      date
    };

    onSave(newReview);   
    setSuccessMsg(editingReview ? "Review updated!" : "Review submitted!"); 
    setTimeout(() => {
      setSuccessMsg("");
      onClose();   
    }, 3000);            
}
  return (
    <form className="review-form" onSubmit={handleSubmit}>
      <h3 className= "reviewform-title">{editingReview ? "Edit Review" : "Add Review"}</h3> 
       {successMsg && (
    <div className="success-message">
      {successMsg}
    </div>
    )}
           
      {/* for Name */}
     <div className="review-fields-row">
      <div className="review-field">
    <label htmlFor="name">Name</label>
        <input
        className="review-input"
        id="name"
        type="text"
        value={name}
        onChange={(e) => setName(e.target.value)}
        required
      />  
      </div>       
      
      {/* Level Dropdown */}  
      <div className="review-field">
      <label>Level</label>
      <select
      className="review-input"
        value={levelName}
        onChange={(e) => setLevelName(e.target.value)}
        required
      >
        <option value="">Select level</option>
        <option value="Beginner">Beginner</option>
        <option value="Intermediate">Intermediate</option>
        <option value="Advanced">Advanced</option>
      </select>   
      </div>
    {/* Input field for Rating */}
     <div className="review-field">
    <label>Rating</label>   
      <select
      className="review-input"
        value={rating}
        onChange={(e) => setRating(Number(e.target.value))}   
        required
      >
        <option value={0}>Select rating</option>
        <option value={1}>1 - Poor</option>
        <option value={2}>2 - Fair</option>
        <option value={3}>3 - Good</option>
        <option value={4}>4 - Very Good</option>
        <option value={5}>5 - Excellent</option>
      </select>
      </div>

      </div>

      {/*Input field for comment*/}
      <div className="review-comment">
      <label>Comment</label>
      <textarea
      className="review-textarea"
        value={comment}
        onChange={(e) => setComment(e.target.value)}
        required
      />
      </div>
      
      {/* Date-Autogenerated */ }
      <input type="hidden" value={date} />
       
      {/* Submit button */}
      <button type="submit" className="submit-btn">
        {editingReview ? "Update" : "Submit"}
      </button>
      
    </form>
    
  );
}

export default ReviewForm;

